### Get the secret ingredient.
GET https://localhost:5081/secret/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImRhbm55Iiwic3ViIjoiZGFubnkiLCJqdGkiOiIyMTQ0MzZlNCIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjEzNTYyIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMjgiLCJodHRwOi8vbG9jYWxob3N0OjUwOTkiLCJodHRwczovL2xvY2FsaG9zdDo1MDgxIl0sIm5iZiI6MTcyMTE0NjE0MywiZXhwIjoxNzI5MDk0OTQzLCJpYXQiOjE3MjExNDYxNDQsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.JKJ0YSOnvSAJ7tWZGmsaxYy6Xm71FEedrz3wTaplwm4
